version: "3.9"
services:
  dns:
    image: flavienperier/dns
    container_name: dns
    restart: always
    depends_on:
      - reverse-proxy
    ports:
      - 127.0.0.1:53:53/udp
    environment:
      SERVER_DOMAIN: "127.0.0.1"
      BASE_PATH: ${DOMAIN}
      SUB_DOMAINS: jupyter
      SUB_DNS: 208.67.222.222 208.67.220.220 1.1.1.1 1.0.0.1 151.80.222.79  

  proxy:
    image: flavienperier/proxy
    container_name: proxy
    restart: always
    depends_on:
      - dns
    volumes:
      - squid:/var/squid/cache
    ports:
      - 127.0.0.1:3128:3128
    environment:
      DNS: dns

  openssl:
    image: flavienperier/openssl
    container_name: openssl
    volumes:
      - ./etc/certificates:/certificates
    environment:
      DOMAIN: ${DOMAIN}
      CERTIFICATES: jupyter 

  reverse-proxy: 
    image: nginx:alpine
    container_name: reverse-proxy
    restart: always
    depends_on:
      - jupyter
    volumes:
      - ./etc/certificates:/etc/certificates:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/sites:/etc/nginx/sites:ro
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443

  jupyter:
    image: flavienperier/jupyter
    container_name: jupyter
    restart: always
    volumes:
      - ./data/jupyter:/opt/notebooks/data
    environment:
      JUPYTER_PASSWORD: ${PASSWORD}

  sandbox-dev:
    image: flavienperier/sandbox-dev
    container_name: sandbox-dev
    restart: always
    volumes:
      - ./data:/home/admin/data
    ports:
      - 127.0.0.1:2201:22
    environment:
      PASSWORD: ${PASSWORD}

  sandbox-hack:
    image: flavienperier/sandbox-hack
    container_name: sandbox-hack
    restart: always
    volumes:
      - ./data:/home/admin/data
    ports:
      - 127.0.0.1:2202:22
    environment:
      PASSWORD: ${PASSWORD}

volumes:
  squid:
